server:
  port: 18089
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: item
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.168.14
    port: 5672
    username: admin
    password: admin
pagepath: E:/cgou/cgou-parent/cgou-web/cgou-web-item/src/main/resources/templates/items