server:
  port: 18085
spring:
  application:
    name: business
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.168.14:3307/changgou_business?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  rabbitmq:
    host: 192.168.168.14
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      profile: dev
      label: master
      uri: http://localhost:9001/
      fail-fast: true
      # 默 认 重 试 的 间 隔 时 间 ， 默 认 1000ms
      retry:
        multiplier: 1.1
        max-attempts: 6
        max-interval: 2000
        initial-interval: 1000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰功能
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
business:
  ad-update-url: http://192.168.168.14/ad_update

