spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: cgou-goods-route
          uri: lb://goods #LoadBalancerClientFilter会作用在url以lb开头的路由利用loadBalancer来获取服务实例
          predicates:
          #- Host=cgou.lilei.xyz**  所有以cgou.lilei.xyz 开头交给
          - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**#所有以brand开头的请求交给goods处理
          filters:
          #- PrefixPath=/brand
          - StripPrefix=1 #过滤请求路径中的第一个路径
          - name: RequestRateLimiter
            args:
              key-resolver: "#{@ipKeyResolver}"
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 10
        - id: cgou-user-route
          uri: lb://user
          predicates:
          - Path=/api/user/**, /api/address/**,/api/areas/**, /api/cities/**, /api/provinces/**
          filters:
            - StripPrefix=1
        - id: cgou-order-route
          uri: lb://order
          predicates:
          - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
          filters:
            - StripPrefix=1

  redis:
    password: 123456
    host: 192.168.168.14
    port: 6379
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      # 收集日志的百分比
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
  # 若 在 同 一 个 注 册 中 心 的 话 可 以 启 用 自 动 发 现 ， 省 略 base-url
  #locator:
    #  discovery:
    #    enabled: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka